services:
  ratatui-docs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ratatui-docs
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - ratatui-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

networks:
  ratatui-network:
    driver: bridge

